server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/rates
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  liquibase:
    change-log: liquibase/db.changelog.xml
    drop-first: true

app:
  queue-name: rates_queue