server:
  port: ${APP_PORT:8086}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESSES:localhost:3305}/${MYSQL_DATABASE:rates}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    addresses: ${RABBIT_ADDRESSES:localhost:5671}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  liquibase:
    change-log: liquibase/db.changelog.xml
    drop-first: true

app:
  queue-name: rates_queue